### ISSUE TITLE
receiving typeerror in tensorflow_fitting_script

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#20]
Trying to execute the tensorflow_fittings_script.py, however, I'm receiving the following error;

gudui@buddy:~/CryptoCurrencyTrader$ python tensorflow_fitting_script.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "tensorflow_fitting_script.py", line 83, in <module>
    strategy_dictionary, data_to_predict, fitting_inputs, fitting_targets = tensorflow_fitting(strategy_dictionary)
  File "tensorflow_fitting_script.py", line 24, in tensorflow_fitting
    data_local, strategy_dictionary)
  File "/home/gudui/CryptoCurrencyTrader/trading_strategy_fitting.py", line 97, in input_processing
    strategy_dictionary)
  File "/home/gudui/CryptoCurrencyTrader/data_input_processing.py", line 379, in generate_training_variables
    data_obj.calculate_indicators(strategy_dictionary, prior_data_obj=prior_data_obj)
  File "/home/gudui/CryptoCurrencyTrader/data_input_processing.py", line 151, in calculate_indicators
    strategy_dictionary['windows'])
  File "/home/gudui/CryptoCurrencyTrader/data_input_processing.py", line 340, in exponential_moving_average
    weights = np.exp(np.linspace(-1., 0., window))
  File "/home/gudui/miniconda2/lib/python2.7/site-packages/numpy/core/function_base.py", line 101, in linspace
    num = _index_deprecate(num)
  File "/home/gudui/miniconda2/lib/python2.7/site-packages/numpy/core/function_base.py", line 19, in _index_deprecate
    i = int(i)
TypeError: int() argument must be a string or a number, not 'list'

**Comment by llens** [comment]
I have the tensorflow script now, 'windows' should be a single int not a list, I had changed it for sklearn and not the other.
