### ISSUE TITLE
Larger candle sizes results in indexError

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#24]
When specifying a higher valid candle_size, e.g. 900 or 1800, the script crashing when calculating expectational average, what could be the cause?

Traceback (most recent call last):
  File "tensorflow_fitting_script.py", line 84, in <module>
    strategy_dictionary, data_to_predict, fitting_inputs, fitting_targets = tensorflow_fitting(strategy_dictionary)
  File "tensorflow_fitting_script.py", line 24, in tensorflow_fitting
    data_local, strategy_dictionary)
  File "/home/gudui/CryptoCurrencyTrader/trading_strategy_fitting.py", line 99, in input_processing
    strategy_dictionary)
  File "/home/gudui/CryptoCurrencyTrader/data_input_processing.py", line 379, in generate_training_variables
    data_obj.calculate_indicators(strategy_dictionary, prior_data_obj=prior_data_obj)
  File "/home/gudui/CryptoCurrencyTrader/data_input_processing.py", line 161, in calculate_indicators
    10 * strategy_dictionary['windows']))
  File "/home/gudui/CryptoCurrencyTrader/data_input_processing.py", line 343, in exponential_moving_average
    ema[:window] = ema[window]
IndexError: index 3000 is out of bounds for axis 0 with size 959

**Comment by llens** [comment]
I would check that with the large candle size, the window is shorter than the total number of candles, if not it will crash. E.G. if n_days = 1, Candles = 1800 then Candles per day = 48. If the window size is larger than this ema will not work.
