### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by kebodev** [llens/CryptoCurrencyTrader#30]
Hello,

i create a file named API_settings.py and i put in my api key and secret. Then i run your code in my terminal like this: python3 portfolio_management_script.py
Downloads are finished, but then it raise this:

Traceback (most recent call last):
  File "portfolio_management_script.py", line 90, in <module>
    **cnn_kwargs)
  File "/Users/kulig/trade/CryptoCurrencyTrader/machine_learning.py", line 62, in tensorflow_cnn_fitting
    optimizer=opt)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 860, in compile
    sample_weight, mask)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 459, in weighted
    score_array = fn(y_true, y_pred)
  File "/Users/kulig/trade/CryptoCurrencyTrader/machine_learning.py", line 121, in custom_loss
    _, cum_log_return = calculate_portfolio_value_backend(y_pred, y_true)
  File "/Users/kulig/trade/CryptoCurrencyTrader/porftfolio_functions.py", line 72, in calculate_portfolio_value_backend
    shrinking_factor = K.concatenate((K.ones((1, K.shape(shrinking_factor)[1])), shrinking_factor), axis=0)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 708, in ones
    return variable(tf.constant_initializer(1., dtype=tf_dtype)(shape),
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py", line 200, in __call__
    self.value, dtype=dtype, shape=shape, verify_shape=verify_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 380, in make_tensor_proto
    if shape is not None and np.prod(shape, dtype=np.int64) == 0:
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2518, in prod
    out=out, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
ValueError: setting an array element with a sequence.

Can you help me? Thank you!

**Comment by kebodev** [comment]
sorry i had to upgrade keras and tensorflow..
